config/routes.rb
Rails.application.routes.draw do
  resources :ultrasonic_readings
  resources :parking_locations do
    resources :parking_spots
  end
  resources :parking_spots
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "parking_locations#index"
end

app/models/parking_location.rb
class ParkingLocation < ApplicationRecord
    has_many :parking_spots


enum status:{
    active:'active',
    development:'development',
    inactive:'inactive'
}
end

app/controllers/parking_locations_controller.rb
class ParkingLocationsController < ApplicationController
  before_action :set_parking_location, only: %i[ show edit update destroy ]

  # GET /parking_locations or /parking_locations.json
  def index
    @parking_locations = ParkingLocation.all
  end

  # GET /parking_locations/1 or /parking_locations/1.json
  def show
  end

  # GET /parking_locations/new
  def new
    @parking_location = ParkingLocation.new
  end

  # GET /parking_locations/1/edit
  def edit
  end

  # POST /parking_locations or /parking_locations.json
  def create
    @parking_location = ParkingLocation.new(parking_location_params)

    respond_to do |format|
      if @parking_location.save
        format.html { redirect_to parking_location_url(@parking_location), notice: "Parking location was successfully created." }
        format.json { render :show, status: :created, location: @parking_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parking_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_locations/1 or /parking_locations/1.json
  def update
    respond_to do |format|
      if @parking_location.update(parking_location_params)
        format.html { redirect_to parking_location_url(@parking_location), notice: "Parking location was successfully updated." }
        format.json { render :show, status: :ok, location: @parking_location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parking_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_locations/1 or /parking_locations/1.json
  def destroy
    @parking_location.destroy

    respond_to do |format|
      format.html { redirect_to parking_locations_url, notice: "Parking location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_location
      @parking_location = ParkingLocation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parking_location_params
      params.require(:parking_location).permit(:street, :status)
    end
end

app/helpers/parking_locations_helper.rb
module ParkingLocationsHelper
end

app/views/parking_locations/_form.html.erb
<%= form_with(model: parking_location, class: "contents") do |form| %>
  <% if parking_location.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(parking_location.errors.count, "error") %> prohibited this parking_location from being saved:</h2>

      <ul>
        <% parking_location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :street %>
    <%= form.text_field :street, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/parking_locations/_parking_location.html.erb
<div id="<%= dom_id parking_location %>">

  <div class="flex">
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block">
      <%= parking_location.status %>
    </p>
    <p class="py-2 px-3">
      <%=link_to parking_location.street, parking_location, class:"hover:underline"%>
    </p>
</div>
    <p class="py-2 px-3 text-sm my-4">
      Parking Spots:<%= parking_location.parking_spots.count%>
    </p>
    <p class="py-2 px-3 text-sm my-4">
      Available:<%= parking_location.parking_spots.where(status:ParkingSpot.statuses[:vacant]).count%>
    </p>

  <% if action_name != "show" %>
    <%= link_to "Edit this parking location", edit_parking_location_path(parking_location), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/parking_locations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing parking location</h1>

  <%= render "form", parking_location: @parking_location %>

  <%= link_to "Show this parking location", @parking_location, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to parking locations", parking_locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/parking_locations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Parking locations</h1>
    <%= link_to "New parking location", new_parking_location_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="parking_locations" class="min-w-full">
    <%= render @parking_locations %>
  </div>
</div>

app/views/parking_locations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New parking location</h1>

  <%= render "form", parking_location: @parking_location %>

  <%= link_to "Back to parking locations", parking_locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/parking_locations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <p class="text-2xl font-bold mb-4"><%=@parking_location.street%></p>
    
    <div class="w-48 my-4">
      <%= link_to "New parking spot", new_parking_location_parking_spot_path(@parking_location), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
    <table class="table-auto w-full text-left  relative">
    <thead>
    <tr>
      <th>Spot</th>
      <th>Status</th>
      <th>Last Reading</th>
    <tr>
    <thead>
    <tbody>
    <% @parking_location.parking_spots.each do |parking_spot|%>
    <tr class="border-b">
      <td class="py-2"><%=link_to parking_spot.name, parking_spot, class:"hover:underline"%></td>
      <td><%=parking_spot.status%></td>
      <td><%=parking_spot.ultrasonic_readings.last&.reading || "-"%></td>
    <tr>
    <%end%>
    </tbody>
    </table>



    <%= link_to "Edit this parking_location", edit_parking_location_path(@parking_location), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this parking_location", parking_location_path(@parking_location), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to parking_locations", parking_locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>