config/routes.rb
Rails.application.routes.draw do
  resources :ultrasonic_readings
  resources :parking_locations do
    resources :parking_spots
  end
  resources :parking_spots
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "parking_locations#index"
end

app/models/ultrasonic_reading.rb
class UltrasonicReading < ApplicationRecord
  belongs_to :parking_spot

  before_create :check_parking_spot


  private
    def check_parking_spot
      if reading <=parking_spot.max_distance
        parking_spot.status=ParkingSpot.statuses[:occupied]
      else
        parking_spot.status=ParkingSpot.statuses[:vacant]
      end
        parking_spot.save!
    end
end

app/controllers/ultrasonic_readings_controller.rb
class UltrasonicReadingsController < ApplicationController
  before_action :set_ultrasonic_reading, only: %i[ show edit update destroy ]

  skip_before_action :verify_authenticity_token, only: [:create ]

  # GET /ultrasonic_readings or /ultrasonic_readings.json
  def index
    @ultrasonic_readings = UltrasonicReading.all
  end

  # GET /ultrasonic_readings/1 or /ultrasonic_readings/1.json
  def show
  end

  # GET /ultrasonic_readings/new
  def new
    @ultrasonic_reading = UltrasonicReading.new
  end

  # GET /ultrasonic_readings/1/edit
  def edit
  end

  # POST /ultrasonic_readings or /ultrasonic_readings.json
  def create
    @ultrasonic_reading = UltrasonicReading.new(ultrasonic_reading_params)

    respond_to do |format|
      if @ultrasonic_reading.save
        format.html { redirect_to ultrasonic_reading_url(@ultrasonic_reading), notice: "Ultrasonic reading was successfully created." }
        format.json { render :show, status: :created, location: @ultrasonic_reading }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ultrasonic_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ultrasonic_readings/1 or /ultrasonic_readings/1.json
  def update
    respond_to do |format|
      if @ultrasonic_reading.update(ultrasonic_reading_params)
        format.html { redirect_to ultrasonic_reading_url(@ultrasonic_reading), notice: "Ultrasonic reading was successfully updated." }
        format.json { render :show, status: :ok, location: @ultrasonic_reading }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ultrasonic_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ultrasonic_readings/1 or /ultrasonic_readings/1.json
  def destroy
    @ultrasonic_reading.destroy

    respond_to do |format|
      format.html { redirect_to ultrasonic_readings_url, notice: "Ultrasonic reading was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ultrasonic_reading
      @ultrasonic_reading = UltrasonicReading.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ultrasonic_reading_params
      params.require(:ultrasonic_reading).permit(:parking_spot_id, :reading)
    end
end

app/helpers/ultrasonic_readings_helper.rb
module UltrasonicReadingsHelper
end

app/views/ultrasonic_readings/_form.html.erb
<%= form_with(model: ultrasonic_reading, class: "contents") do |form| %>
  <% if ultrasonic_reading.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ultrasonic_reading.errors.count, "error") %> prohibited this ultrasonic_reading from being saved:</h2>

      <ul>
        <% ultrasonic_reading.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :parking_spot_id %>
    <%= form.text_field :parking_spot_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :reading %>
    <%= form.text_field :reading, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/ultrasonic_readings/_ultrasonic_reading.html.erb
<div id="<%= dom_id ultrasonic_reading %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Parking spot:</strong>
    <%= ultrasonic_reading.parking_spot_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Reading:</strong>
    <%= ultrasonic_reading.reading %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this ultrasonic reading", ultrasonic_reading, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this ultrasonic reading", edit_ultrasonic_reading_path(ultrasonic_reading), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/ultrasonic_readings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ultrasonic reading</h1>

  <%= render "form", ultrasonic_reading: @ultrasonic_reading %>

  <%= link_to "Show this ultrasonic reading", @ultrasonic_reading, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to ultrasonic readings", ultrasonic_readings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ultrasonic_readings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ultrasonic readings</h1>
    <%= link_to "New ultrasonic reading", new_ultrasonic_reading_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="ultrasonic_readings" class="min-w-full">
    <%= render @ultrasonic_readings %>
  </div>
</div>

app/views/ultrasonic_readings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ultrasonic reading</h1>

  <%= render "form", ultrasonic_reading: @ultrasonic_reading %>

  <%= link_to "Back to ultrasonic readings", ultrasonic_readings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ultrasonic_readings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ultrasonic_reading %>

    <%= link_to "Edit this ultrasonic_reading", edit_ultrasonic_reading_path(@ultrasonic_reading), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this ultrasonic_reading", ultrasonic_reading_path(@ultrasonic_reading), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to ultrasonic_readings", ultrasonic_readings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>