config/routes.rb
Rails.application.routes.draw do
  resources :ultrasonic_readings
  resources :parking_locations do
    resources :parking_spots
  end
  resources :parking_spots
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "parking_locations#index"
end

app/models/parking_spot.rb
class ParkingSpot < ApplicationRecord
  belongs_to :parking_location
  has_many :ultrasonic_readings
  

  enum status:{
    occupied:'occupied',
    vacant:'vacant'
  }

  validates :status, inclusion:{in:statuses.keys, message: "%{value} is not a valid status"}
end

app/controllers/parking_spots_controller.rb
class ParkingSpotsController < ApplicationController
  before_action :set_parking_spot, only: %i[ show edit update destroy ]
  rescue_from ArgumentError, with: :invalid_argument_error

  # GET /parking_spots or /parking_spots.json
  def index
    @parking_spots = ParkingSpot.all
  end

  # GET /parking_spots/1 or /parking_spots/1.json
  def show
  end

  # GET /parking_spots/new
  def new
    @parking_spot = ParkingSpot.new
    @parking_spot.parking_location_id = params[:parking_location_id]
  end

  # GET /parking_spots/1/edit
  def edit
  end

  # POST /parking_spots or /parking_spots.json
  def create
    @parking_spot = ParkingSpot.new(parking_spot_params)

    respond_to do |format|
      if @parking_spot.save
        format.html { redirect_to parking_spot_url(@parking_spot), notice: "Parking spot was successfully created." }
        format.json { render :show, status: :created, location: @parking_spot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parking_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_spots/1 or /parking_spots/1.json
  def update
    respond_to do |format|
      if @parking_spot.update(parking_spot_params)
        format.html { redirect_to parking_spot_url(@parking_spot), notice: "Parking spot was successfully updated." }
        format.json { render :show, status: :ok, location: @parking_spot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parking_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_spots/1 or /parking_spots/1.json
  def destroy
    @parking_spot.destroy

    respond_to do |format|
      format.html { redirect_to parking_spots_url, notice: "Parking spot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_spot
      @parking_spot = ParkingSpot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parking_spot_params
      params.require(:parking_spot).permit(:parking_location_id, :name, :status, :max_distance)
    end

    def invalid_argument_error(exceptions)
      flash[:alert] =  exceptions.message
      flash[:notice] =  exceptions.message
      action = params[:action] == "create" ? :new : :edit
      redirect_to action: action, status: :unprocessable_entity
    end
end

app/helpers/parking_spots_helper.rb
module ParkingSpotsHelper
end

app/views/parking_spots/_form.html.erb
<% if alert.present? %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="aler"><%= alert%></p>
  <% end %>

<%= form_with(model: parking_spot, class: "contents") do |form| %>
  <% if parking_spot&.errors&.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(parking_spot.errors.count, "error") %> prohibited this parking_spot from being saved:</h2>

      <ul>
        <% parking_spot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.hidden_field :parking_location_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status, ParkingSpot.statuses,{}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :max_distance %>
    <%= form.text_field :max_distance, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/parking_spots/_parking_spot.html.erb
<div id="<%= dom_id parking_spot %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Parking location:</strong>
    <%= parking_spot.parking_location_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= parking_spot.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= parking_spot.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Max distance:</strong>
    <%= parking_spot.max_distance %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this parking spot", parking_spot, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this parking spot", edit_parking_spot_path(parking_spot), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/parking_spots/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing parking spot</h1>

  <%= render "form", parking_spot: @parking_spot %>

  <%= link_to "Show this parking spot", @parking_spot, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to parking spots", parking_spots_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/parking_spots/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Parking spots</h1>
    <%= link_to "New parking spot", new_parking_spot_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="parking_spots" class="min-w-full">
    <%= render @parking_spots %>
  </div>
</div>

app/views/parking_spots/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New parking spot</h1>

  <%= render "form", parking_spot: @parking_spot %>

  <%= link_to "Back to parking spots", parking_spots_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/parking_spots/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @parking_spot %>

    <%= link_to "Edit this parking_spot", edit_parking_spot_path(@parking_spot), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this parking_spot", parking_spot_path(@parking_spot), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to parking_spots", parking_spots_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>